config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/ccdetect:
      branch: main
      repo: https://github.com/stevenjgibbons/ccdetect
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/ccdetect git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-zucchini-quoll.sh
        container: qc.acc_silly-denim-whale
  QC.Doc:
    repos:
      github.com/stevenjgibbons/ccdetect find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-khaki-dane.sh
        container: qc.doc_zippy-saffron-turtle
      github.com/stevenjgibbons/ccdetect git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-amaranth-millipede.sh
        container: qc.doc_pokey-jade-akbash
      github.com/stevenjgibbons/ccdetect markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-thistle-zebu.sh
        container: qc.doc_snoopy-salmon-wallaby
  QC.Lic:
    repos:
      github.com/stevenjgibbons/ccdetect licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-ecru-wallaby.sh
        container: qc.lic_sleepy-aqua-jaguar
  QC.Sec:
    repos:
      github.com/stevenjgibbons/ccdetect bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lemon-seahorse.sh
        container: qc.sec_stealthy-pumpkin-sponge
  QC.Sty:
    repos:
      github.com/stevenjgibbons/ccdetect flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-saffron-liger.sh
        container: qc.sty_gimpy-malachite-chimpanzee
  QC.Uni:
    repos:
      github.com/stevenjgibbons/ccdetect pytest:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-persimmon-whippet.sh
        container: qc.uni_messy-burgundy-ferret
  QC.Ver:
    repos:
      github.com/stevenjgibbons/ccdetect get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-turquoise-numbat.sh
        container: qc.ver_stuffy-saffron-kudu
timeout: 5400
