config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/ccdetect:
      branch: main
      repo: https://github.com/stevenjgibbons/ccdetect
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/ccdetect git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-khaki-heron.sh
        container: qc.acc_sloppy-razzmatazz-caterpillar
  QC.Doc:
    repos:
      github.com/stevenjgibbons/ccdetect find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-thistle-bombay.sh
        container: qc.doc_muzzy-olive-tarantula
      github.com/stevenjgibbons/ccdetect git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-heliotrope-kiwi.sh
        container: qc.doc_beady-myrtle-koala
      github.com/stevenjgibbons/ccdetect markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-alizarin-kingfisher.sh
        container: qc.doc_dorky-eggplant-armadillo
  QC.Lic:
    repos:
      github.com/stevenjgibbons/ccdetect licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-magnolia-kiwi.sh
        container: qc.lic_boozy-xanthic-rhinoceros
  QC.Sec:
    repos:
      github.com/stevenjgibbons/ccdetect bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-malachite-buffalo.sh
        container: qc.sec_surly-cobalt-millipede
  QC.Sty:
    repos:
      github.com/stevenjgibbons/ccdetect flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-tomato-panda.sh
        container: qc.sty_beady-corn-crab
  QC.Uni:
    repos:
      github.com/stevenjgibbons/ccdetect pytest:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-myrtle-wolverine.sh
        container: qc.uni_flabby-celadon-markhor
  QC.Ver:
    repos:
      github.com/stevenjgibbons/ccdetect get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-lilac-skunk.sh
        container: qc.ver_homely-chestnut-coati
timeout: 5400
